# Generated by Django 6.0.5 on 2026-05-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('short_description', models.CharField(max_length=280)),
                ('description', models.TextField()),
                ('problem_statement', models.TextField(blank=True)),
                ('dataset_information', models.TextField(blank=True)),
                ('tools_used', models.TextField(blank=True)),
                ('steps_performed', models.TextField(blank=True)),
                ('insights_discovered', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('technologies_used', models.CharField(help_text='Comma separated values.', max_length=260)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_link', models.URLField(blank=True)),
                ('dashboard_embed_link', models.URLField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
