# Generated by Django 6.0.5 on 2026-05-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='powerbi_embed_mode',
            field=models.CharField(choices=[('public', 'Public link'), ('private', 'Private / secure')], default='public', help_text='Choose public embedding for publish-to-web or private for secure embed later.', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='powerbi_report_id',
            field=models.CharField(blank=True, help_text='Power BI report ID from the service workspace.', max_length=128),
        ),
        migrations.AddField(
            model_name='project',
            name='powerbi_workspace_id',
            field=models.CharField(blank=True, help_text='Power BI workspace/group ID.', max_length=128),
        ),
    ]
